name: Build Android

on: [push, pull_request]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install capacitor
        run: npm install -g capacitor

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Add Android platform
        run: ionic capacitor platform add android@latest
        
      - name: Create android build folder
        run: npx ionic capacitor copy android && npx cap sync android
        
      - name: Build final APK Gradlew
        run: cd android && chmod +x gradlew && ./gradlew assembleDebug

      - name: Zip
        run: zip -r /tmp/sfof_apk.zip /home/runner/work
        shell: bash
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/sfof_apk.zip
          asset_name: sfof_apk.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "sfof_apk"



          
